# Generated by Django 2.2.3 on 2019-11-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20190618_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='dkftest',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
