# Generated by Django 2.2.3 on 2019-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_productvariant_dkftest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
