# Generated by Django 2.2.3 on 2019-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0098_auto_20191124_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='type_ini',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
