"""
Django settings for payment_lipay project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b+$!k2td&b7m&ll7-d06sb!y*du$@a@shooq0^%a#0x-@_(73v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'alipayTest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
   # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'payment_lipay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'payment_lipay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME':  'django_alipay',
#         'USER': 'root',
#         'PASSWORD':'123456',
#         'HOST': 'localhost',
#         'PORT': '3306'
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static")
]


# 设置支付宝配置
# AliPayConfig = {
#     'app_id': "2016092700607535",
#     'ALIPAY_URL': "https://openapi.alipaydev.com/gateway.do",
#     'ALIPAY_DEBUG': True,
#     'return_url':'http://127.0.0.1:8008/pay/',
#     'notify_url':'http://127.0.0.1:8008/pay/',
#     'merchant_private_key_path':'alipay/keys/app_private_key.pem',
#     'alipay_public_key_path':'alipay/keys/alipay_public_key.pem',
# }
# 支付宝参数配置
class AliPayConfig(object):
    # 正式启用时需要重新配置app_id ，merchant_private_key_path ，alipay_public_key_path
    app_id = "2016092700607535"  # APPID  沙箱应用

    # 支付完成后支付宝向这里发送一个post请求，如果识别为局域网ip，支付宝找不到，alipay_result（）接受不到这个请求
    notify_url = "http://39.98.183.97/alipay_result2/"

    # 支付完成后跳转的地址
    return_url = "http://39.98.183.97/pay/alipay_result2/"

    # 应用私钥
    merchant_private_key_path = "alipayTest/keys/app_private_key.pem"
    # 支付宝公钥
    alipay_public_key_path = "alipayTest/keys/alipay_public_key.pem"  # 验证支付宝回传消息使用

    # 微信的证书
    wx_apiclient_cert_path = "alipayTest/keys/wx/apiclient_cert.pem"
    wx_apiclient_key_path = "alipayTest/keys/wx/apiclient_key.pem"
